### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by edwinchenloo** [theeyeofcthulhu/clidle#1]
the word was 'shorn'

my guess was 'doorn'.  The first 'o' was yellow, the second 'o' was green.  Since there is only one 'o' in the word the 'o'  that was marked yellow should have remained white.

**Comment by theeyeofcthulhu** [comment]
Thank you for noticing! I fixed this in https://github.com/theeyeofcthulhu/clidle/commit/d870641faf1d033b139f120a25e53e0e526ffc64.
